[package]
name = "shoshinwhitelist"
version = "0.0.1"
published-at = "0x7d587bcdeea388c1ebac59054cd89ce7496139a655a23954567c7adcba305bca"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "devnet" }

[addresses]
shoshinwhitelist =  "0x7d587bcdeea388c1ebac59054cd89ce7496139a655a23954567c7adcba305bca"
sui =  "0x2"

# 0xcd5d4ab8b3d542947ddfebde7560c98b9a326b0959118dd0dbe790bffa67cea4
