[package]
name = "shoshinmintattribute"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "devnet" }
shoshinattribute = { local = "../attribute" }


[addresses]
shoshinmintattribute =  "0x0"
sui =  "0x2"

