[package]
name = "shoshinlaunchpad"
version = "0.0.0"




[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "devnet" }
# shoshinnft = { local = "../nft" }


[addresses]
shoshinlaunchpad =  "0x0"
sui = "0x2"



