[package]
name = "shoshinlaunchpad"
version = "0.0.0"
published-at = "0x204cd01b4917e9bdcc4ea38a31a3f7c0a5cc2661c386824c0ced3516eae95846"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "devnet" }
shoshinwhitelist = { local = "../whitelist" }

[addresses]
shoshinlaunchpad =  "0x204cd01b4917e9bdcc4ea38a31a3f7c0a5cc2661c386824c0ced3516eae95846"
sui = "0x2"


